# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1389872005);
user_pref("app.update.lastUpdateTime.background-update-timer", 1389871885);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1389872125);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1389871645);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1389871765);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.dir", "C:\\Git\\cat\\CAT.FrontEnd.Tests\\TestResults");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131205075310");
user_pref("browser.slowStartup.averageTime", 1083);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20131205075310");
user_pref("browser.startup.homepage_override.mstone", "26.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1389687408692");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1389871587066");
user_pref("datareporting.policy.firstRunTime", "1389601008692");
user_pref("datareporting.sessions.current.activeTicks", 15);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 708);
user_pref("datareporting.sessions.current.main", 50);
user_pref("datareporting.sessions.current.sessionRestored", 751);
user_pref("datareporting.sessions.current.startTime", "1389871524764");
user_pref("datareporting.sessions.current.totalTime", 1588);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1389601008178,\"a\":148,\"t\":2030,\"c\":true,\"m\":47,\"fp\":1757,\"sr\":2482}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1389603152979,\"a\":16,\"t\":82,\"c\":true,\"m\":37,\"fp\":522,\"sr\":559}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1389604427832,\"a\":71,\"t\":443,\"c\":true,\"m\":54,\"fp\":514,\"sr\":602}");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:26.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{4ED1F68A-5463-4931-9384-8FFF5ED91D92}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\McAfee\\\\SiteAdvisor\",\"mtime\":1389853424411,\"rdfTime\":1385017666000}}},{\"name\":\"app-global\",\"addons\":{\"{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}\",\"mtime\":1387438519619,\"rdfTime\":1381301882000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1387438527786,\"rdfTime\":1387438527594}}}]");
user_pref("extensions.lastAppVersion", "26.0");
user_pref("extensions.lastPlatformVersion", "26.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20131205075310");
user_pref("gecko.mstone", "26.0");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("idle.lastDailyNotification", 1389871950);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1389871950);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1389871950);
user_pref("toolkit.startup.last_success", 1389871524);
user_pref("toolkit.telemetry.previousBuildID", "20131205075310");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1392193012);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
