using System;
using System.Threading;
using NUnit.Framework;
using OpenQA.Selenium;
using System.Collections.Generic;
using System.Windows.Forms;

namespace AbbyyLs.CAT.Function.Selenium.Tests
{
    public class GlossaryTest : BaseTest
    {
        public GlossaryTest(string url, string workspaceUrl, string browserName)
            : base(url, workspaceUrl, browserName)
        {

        }

        [SetUp]
        public void Setup()
        {
            // Авторизация
            Authorization();

            // Перейти на вкладку Glossary
            SwitchGlossaryTab();
        }

        protected void SwitchCurrentGlossary(string glossaryName)
        {
            // Перейти на страницу глоссария
            string xPath = "//tr[contains(@class, 'js-glossary-row')]/td[1]/p[text()='" + glossaryName + "']";
            Driver.FindElement(By.XPath(xPath)).Click();
        }

        protected void CreateGlossaryByName(string glossaryName, bool bNeedWaitSuccessSave = true)
        {
            // Открыть форму создания глоссария
            OpenCreateGlossary();

            // Ввести имя
            Driver.FindElement(By.XPath(
                ".//div[contains(@class,'js-popup-edit-glossary')][2]//input[contains(@class,'js-glossary-name')]")).
                SendKeys(glossaryName);

            // Добавить комментарий
            Driver.FindElement(By.XPath(
                ".//div[contains(@class,'js-popup-edit-glossary')][2]//textarea[contains(@name,'Comment')]")).
                SendKeys("Test Glossary Generated by Selenium");

            // Нажать сохранить
            Driver.FindElement(By.XPath(
               ".//div[contains(@class,'js-popup-edit-glossary')][2]//span[contains(@class,'js-save')]")).Click();

            if (bNeedWaitSuccessSave)
            {
                // Ожидание успешного сохранения
                Wait.Until((d) => d.FindElement(By.XPath(".//span[contains(@class,'js-add-concept')]")).Displayed);
            }
            else
            {
                Thread.Sleep(1000);
            }
        }

        protected bool GetIsExistGlossary(string glossaryName)
        {
            // Получить: существует ли глоссарий с таким именем
            bool isExist = false;
            setDriverTimeoutMinimum();
            IList<IWebElement> glossaryList = Driver.FindElements(By.XPath("//tr[contains(@class, 'js-glossary-row')]/td[1]/p"));
            foreach (IWebElement el in glossaryList)
            {
                if (el.Text == glossaryName)
                {
                    isExist = true;
                    break;
                }
            }
            setDriverTimeoutDefault();
            return isExist;
        }

        protected string GetUniqueGlossaryName()
        {
            // Получить уникальное имя глоссария (т.к. добавляется точная дата и время, то не надо проверять, есть ли такой глоссарий в списке)
            return GlossaryName + DateTime.Now.ToString();
        }

        protected void OpenCreateGlossary()
        {
            // Нажать кнопку Create a glossary
            Driver.FindElement(By.XPath(
                ".//span[contains(@class,'js-create-glossary-button')]//a[contains(@class,'g-btn__text g-redbtn__text')]")).Click();
            // ждем загрузку формы
            Wait.Until((d) => d.FindElement(By.XPath(
                ".//div[contains(@class,'js-popup-edit-glossary')][2]")));
        }

        protected string CreateGlossaryAndReturnToGlossaryList()
        {
            // Получить уникальное имя для глоссария
            string glossaryName = GetUniqueGlossaryName();
            // Создать глоссарий
            CreateGlossaryByName(glossaryName);
            // Перейти к списку глоссариев
            SwitchGlossaryTab();
            return glossaryName;
        }

        protected int GetCountOfItems()
        {
            setDriverTimeoutMinimum();
            int result = Driver.FindElements(By.XPath(".//tr[contains(@class, 'js-concept-row')]")).Count;
            setDriverTimeoutDefault();
            return result;
        }

        protected void OpenEditGlossaryStructure()
        {
            // Открыть Редактирование глоссария
            Wait.Until((d) => d.FindElement(By.XPath(
                ".//span[contains(@class,'js-edit-submenu')]"))).Click();
            // Выбрать Редактирование структуры
            Wait.Until((d) => d.FindElement(By.XPath(
                ".//div[contains(@class,'js-edit-structure-btn')]"))).Click();
            // Задержка, чтобы не появлялось сообщение, что структура глоссария изменена другим пользователем
            Thread.Sleep(2000);
            // Дождаться появления формы
            Wait.Until((d) => d.FindElement(By.XPath(
                ".//div[contains(@class,'js-popup-edit-structure')]")));
        }

        protected void EditGlossaryStructureAddField()
        {
            OpenEditGlossaryStructure();

            // Найти невыбранное поле и добавить его
            string attributeValue = "";
            // Получить список полей
            IList<IWebElement> allFields = Driver.FindElements(By.XPath(".//table[contains(@class, 'js-predefined-attrs-table concept')]//tr[contains(@class, 'l-editgloss__tr js-attr-row')]"));
            for (int i = 0; i < allFields.Count; ++i)
            {
                attributeValue = allFields[i].GetAttribute("class");
                // Если поле не скрыто, нажать на него
                if (!attributeValue.Contains("g-hidden"))
                {
                    // Получить xPath текущей строки
                    string xPath = ".//table[contains(@class, 'js-predefined-attrs-table concept')]//tr[contains(@class, 'l-editgloss__tr js-attr-row')][" + (i + 1).ToString() + "]/td[1]";
                    // Выбрать строку
                    Driver.FindElement(By.XPath(xPath)).Click();
                    // Добавить
                    Wait.Until((d) => d.FindElement(By.XPath(
                        ".//span[contains(@class,'js-add-tbx-attribute')]"))).Click();
                    Thread.Sleep(500);
                    break;
                }
            }

            // Сохранить
            Driver.FindElement(By.XPath(".//div[contains(@class, 'js-popup-buttons')]//span[contains(@class, 'js-save')]")).Click();
            // Дождаться закрытия формы
            Thread.Sleep(1000);
        }

        protected void CreateItemAndSave(string firstTerm = "", string secondTerm = "")
        {
            // Открыть форму добавления термина и заполнить поля
            FillCreateItem(firstTerm, secondTerm);
            // Расширить окно, чтобы кнопка была видна, иначе Selenium ее "не видит" и выдает ошибку
            Driver.Manage().Window.Maximize();
            // Нажать Сохранить
            Driver.FindElement(By.XPath(".//tr[contains(@class, 'js-concept-row js-editing opened')]//a[contains(@class, 'js-save-btn')]")).Click();
            Thread.Sleep(2000);
        }

        protected void FillCreateItem(string firstTerm = "", string secondTerm = "")
        {
            // Нажать New item
            Wait.Until((d) => d.FindElement(By.XPath(".//span[contains(@class,'js-add-concept')]"))).Click();
            // Дождаться появления строки для ввода
            Wait.Until((d) => d.FindElement(By.XPath(".//table[contains(@class,'js-concepts')]")));
            // Заполнить термин
            if (firstTerm.Length == 0)
            {
                firstTerm = "Term First Language" + DateTime.Now.ToString();
            }
            Driver.FindElement(By.XPath(".//tr[contains(@class, 'js-concept-row js-editing')]/td[1]//input")).SendKeys(firstTerm);
            if (secondTerm.Length == 0)
            {
                secondTerm = "Term Second Language" + DateTime.Now.ToString();
            }
            Driver.FindElement(By.XPath(".//tr[contains(@class, 'js-concept-row js-editing')]/td[2]//input")).SendKeys(secondTerm);
        }

        protected void SuggestTermAndSave(string termFirst, string termSecond, bool isNeedSelectGlossary = false, string glossaryName = "")
        {
            // Открыть форму предложения термина и заполнить полня
            SuggestTermFillTerms(termFirst, termSecond);
            if (isNeedSelectGlossary)
            {
                // Открыть список с глоссариями
                Driver.FindElement(By.XPath(".//span[contains(@class, 'js-dropdown addsuggglos')]")).Click();
                Wait.Until((d) => d.FindElement(By.XPath(".//span[contains(@class, 'js-dropdown__list addsuggglos')]")).Enabled);
                // Выбрать наш первый созданный глоссарий в выпавшем списке
                string xPathFirstGlossary = ".//span[contains(@class, 'js-dropdown__item addsuggglos')][@title='" + glossaryName + "']";
                Driver.FindElement(By.XPath(xPathFirstGlossary)).Click();
            }

            // Сохранить
            Driver.FindElement(By.XPath(".//input[contains(@class, 'js-save-btn')]")).Click();
            Thread.Sleep(2000);
        }

        protected void SuggestTermFillTerms(string suggestTermFirst, string suggestTermSecond)
        {
            // Нажать Предложить термин
            Driver.FindElement(By.XPath(".//span[contains(@class, 'g-redbtn js-add-suggest')]//a")).Click();
            Wait.Until((d) => d.FindElement(By.XPath(".//div[contains(@class,'js-popup-bd js-add-suggest-popup')]")).Displayed);
            // Заполнить термин
            Driver.FindElement(By.XPath(
                ".//div[contains(@class, 'l-addsugg__contr lang js-language')][1]//input[contains(@class, 'js-addsugg-term')]"))
                .SendKeys(suggestTermFirst);
            Driver.FindElement(By.XPath(
                ".//div[contains(@class, 'l-addsugg__contr lang js-language')][2]//input[contains(@class, 'js-addsugg-term')]"))
                .SendKeys(suggestTermSecond);
        }

        protected string GetSuggestTermRowsXPath()
        {
            // Вернуть xPath строк с предложенными терминами
            return ".//tr[contains(@class, 'js-suggest-row')]/td[contains(@class, 'js-glossary-cell')]//p";
        }

        protected void FillNewItemExtended()
        {
            // Нажать Add у первого языка
            string xPath = ".//div[contains(@class, 'js-terms-tree')]//div[contains(@class, 'l-corprtree__langbox')][1]//span[contains(@class, 'js-add-term')]";
            Driver.FindElement(By.XPath(xPath)).Click();
            // Ввести текст
            string termText = "Example Term Text " + DateTime.Now.ToString();
            Driver.FindElement(By.XPath(".//span[contains(@class,'js-term-editor')]//input")).SendKeys(termText);
            // Нажать Add у второго языка
            xPath = ".//div[contains(@class, 'js-terms-tree')]//div[contains(@class, 'l-corprtree__langbox')][2]//span[contains(@class, 'js-add-term')]";
            Driver.FindElement(By.XPath(xPath)).Click();
            // Ввести текст
            Driver.FindElement(By.XPath(".//div[contains(@class,'l-corprtree__langbox')][2]//span[contains(@class,'js-term-editor')]//input")).SendKeys(termText);
        }


    }
}
