# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1386752227);
user_pref("app.update.lastUpdateTime.background-update-timer", 1386752107);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1386752347);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1386771747);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1386751987);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131205075310");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 857);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20131205075310");
user_pref("browser.startup.homepage_override.mstone", "26.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":3}");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1386837950438");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1386854160796");
user_pref("datareporting.policy.firstRunTime", "1386751550438");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 813);
user_pref("datareporting.sessions.current.main", 72);
user_pref("datareporting.sessions.current.sessionRestored", 858);
user_pref("datareporting.sessions.current.startTime", "1386854097638");
user_pref("datareporting.sessions.current.totalTime", 112);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.0", "{\"s\":1386751541924,\"a\":18,\"t\":96,\"c\":true,\"m\":65,\"fp\":1512,\"sr\":10362}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1386751638941,\"a\":4,\"t\":18,\"c\":true,\"m\":2,\"fp\":675,\"sr\":743}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1386751657191,\"a\":33,\"t\":201,\"c\":true,\"m\":1,\"fp\":584,\"sr\":656}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1386751866661,\"a\":90,\"t\":15457,\"c\":true,\"m\":58,\"fp\":612,\"sr\":653}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1386771626935,\"a\":24,\"t\":203,\"c\":true,\"m\":50,\"fp\":634,\"sr\":677}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.csharpformatters@seleniumhq.org.install-event-fired", true);
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7Ba6fd85ed-e919-4a43-a5af-8da18bda539f%7D:2.4.0,rubyformatters%40seleniumhq.org:2.4.0,pythonformatters%40seleniumhq.org:2.4.0,javaformatters%40seleniumhq.org:2.4.0,csharpformatters%40seleniumhq.org:2.4.0,selenium_ide_buttons%40egarracingteam.com.ar:1.2.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:26.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1386751529758,\"rdfTime\":1386264433000}}},{\"name\":\"app-profile\",\"addons\":{\"csharpformatters@seleniumhq.org\":{\"descriptor\":\"C:\\\\Users\\\\n.sokolov\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\59xakqr5.default\\\\extensions\\\\csharpformatters@seleniumhq.org.xpi\",\"mtime\":1386751630695},\"javaformatters@seleniumhq.org\":{\"descriptor\":\"C:\\\\Users\\\\n.sokolov\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\59xakqr5.default\\\\extensions\\\\javaformatters@seleniumhq.org.xpi\",\"mtime\":1386751630681},\"pythonformatters@seleniumhq.org\":{\"descriptor\":\"C:\\\\Users\\\\n.sokolov\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\59xakqr5.default\\\\extensions\\\\pythonformatters@seleniumhq.org.xpi\",\"mtime\":1386751630692},\"rubyformatters@seleniumhq.org\":{\"descriptor\":\"C:\\\\Users\\\\n.sokolov\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\59xakqr5.default\\\\extensions\\\\rubyformatters@seleniumhq.org.xpi\",\"mtime\":1386751630679},\"selenium_ide_buttons@egarracingteam.com.ar\":{\"descriptor\":\"C:\\\\Users\\\\n.sokolov\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\59xakqr5.default\\\\extensions\\\\selenium_ide_buttons@egarracingteam.com.ar.xpi\",\"mtime\":1386751657280},\"{a6fd85ed-e919-4a43-a5af-8da18bda539f}\":{\"descriptor\":\"C:\\\\Users\\\\n.sokolov\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\59xakqr5.default\\\\extensions\\\\{a6fd85ed-e919-4a43-a5af-8da18bda539f}.xpi\",\"mtime\":1386751630689}}}]");
user_pref("extensions.javaformatters@seleniumhq.org.install-event-fired", true);
user_pref("extensions.lastAppVersion", "26.0");
user_pref("extensions.lastPlatformVersion", "26.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pythonformatters@seleniumhq.org.install-event-fired", true);
user_pref("extensions.rubyformatters@seleniumhq.org.install-event-fired", true);
user_pref("extensions.selenium-ide.baseURL", "http://code.google.com/");
user_pref("extensions.selenium-ide.baseURLHistory.0", "http://code.google.com/");
user_pref("extensions.selenium-ide.baseURLHistory.length", "1");
user_pref("extensions.selenium-ide.currentVersion", "2.4.0");
user_pref("extensions.selenium-ide.lastSavedTestCase", "");
user_pref("extensions.selenium-ide.lastSavedTestSuite", "");
user_pref("extensions.selenium-ide.pluginsData", "[{\"id\":\"rubyformatters@seleniumhq.org\",\"installed\":false,\"code\":{\"ideExtensions\":[],\"userExtensions\":[],\"formatters\":[]},\"options\":{\"disabled\":false,\"autoDisabled\":false}},{\"id\":\"pythonformatters@seleniumhq.org\",\"installed\":false,\"code\":{\"ideExtensions\":[],\"userExtensions\":[],\"formatters\":[]},\"options\":{\"disabled\":false,\"autoDisabled\":false}},{\"id\":\"javaformatters@seleniumhq.org\",\"installed\":false,\"code\":{\"ideExtensions\":[],\"userExtensions\":[],\"formatters\":[]},\"options\":{\"disabled\":false,\"autoDisabled\":false}},{\"id\":\"csharpformatters@seleniumhq.org\",\"installed\":false,\"code\":{\"ideExtensions\":[],\"userExtensions\":[],\"formatters\":[]},\"options\":{\"disabled\":false,\"autoDisabled\":false}}]");
user_pref("extensions.selenium_ide_buttons@egarracingteam.com.ar.install-event-fired", true);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.{a6fd85ed-e919-4a43-a5af-8da18bda539f}.install-event-fired", true);
user_pref("gecko.buildID", "20131205075310");
user_pref("gecko.mstone", "26.0");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("idle.lastDailyNotification", 1386753751);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1386753752);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1386753752);
user_pref("toolkit.startup.last_success", 1386854097);
user_pref("toolkit.telemetry.previousBuildID", "20131205075310");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1389343556);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
